# default demo stack: steady workflow
version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: builder
    image: nestjs-event-driven-demo:latest
    ports:
      - 3000:3000
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    volumes:
      - .:/app
      - node:/app/node_modules

  cron:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: builder
    image: nestjs-event-driven-demo:latest
    depends_on:
      - redis
    environment:
      - CONTAINER_ROLE=cron
      - REDIS_HOST=redis
    volumes:
      - .:/app
      - node:/app/node_modules

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: builder
    image: nestjs-event-driven-demo:latest
    depends_on:
      - redis
    environment:
      - CONTAINER_ROLE=worker
      - REDIS_HOST=redis
    volumes:
      - .:/app
      - node:/app/node_modules

  cron-issue1:
    profiles:
      - issue1
    extends:
      cron
    environment:
      - CONTAINER_ROLE=cron_issue1

  worker-step1:
    profiles:
      - step1
    extends:
      worker
    environment:
      - CONTAINER_ROLE=worker_1

  cron-step1:
    profiles:
      - step1
      - step2
    extends:
      cron
    environment:
      - CONTAINER_ROLE=cron_1

  cron-step2:
    profiles:
      - step2
    extends:
      cron
    environment:
      - CONTAINER_ROLE=cron_1

  worker-trade:
    profiles:
      - step2
    extends:
      worker
    environment:
      - CONTAINER_ROLE=worker_trade

  worker-default:
    profiles:
      - step2
    extends:
      worker
    environment:
      - CONTAINER_ROLE=worker_default

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

volumes:
  node:
